//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMSCourseStudentTesting.Entityies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocol
    {
        public System.DateTime currentDateTime { get; set; }
        public string currentIP { get; set; }
        public string UserName { get; set; }
        public string OperationType { get; set; }
        public string ObjectName { get; set; }
        public string AttributeName { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
    }
}
